global:
  environment: development

gateway:
  name: api-gateway
  replicaCount: 1
  image:
    repository: gihaa/as-gateway
    tag: latest
  service:
    type: NodePort  # Keeping NodePort for the gateway (optional if you also want it public)
    port: 80
    targetPort: 3000
    nodePort: 31000

userService:
  name: user-service
  replicaCount: 1
  image:
    repository: gihaa/fortify-now-auth-service
    tag: latest
  service:
    type: LoadBalancer  # Change this from ClusterIP to NodePort to expose it publicly
    port: 3001
    targetPort: 3001
    nodePort: 32000  # Set this port to be accessed publicly

database:
  user: "avnadmin"
  password: "AVNS_lP0uW9A3_MC4As3h-NL"
  host: "pg-122ba407-gihansudeeparandimal-f684.g.aivencloud.com"
  port: "17670"
  name: "defaultdb"

jwt:
  secret: "your_jwt_secret"
  expiresIn: "30d"
