global:
  environment: development

gateway:
  name: api-gateway
  replicaCount: 1
  image:
    repository: gihaa/as-gateway
    tag: latest
  service:
    type: NodePort       
    port: 80       
    targetPort: 3000     
    nodePort: 31000    

userService:
  name: user-service
  replicaCount: 1
  image:
    repository: gihaa/as-user-service
    tag: latest
  service:
    type: ClusterIP
    port: 5000

database:
  user: "17670"
  password: "your_password"
  host: "fortify-db"
  port: "17670"
  name: "defaultdb"

jwt:
  secret: "your_jwt_secret"
  expiresIn: "30d"